import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f0f5fa",
    paddingTop: 60,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 25,
    marginBottom: 20,
  },
  headerLogo: {
    width: 150,
    height: 65,
  },
  headerIcons: {
    flexDirection: "row",
    gap: 15,
    alignItems: "center",
  },
  card: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 20,
    marginHorizontal: 25,
    marginBottom: 40,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4.5 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  cardInner: {
    flex: 1,
    borderRadius: 20,
    overflow: "hidden",
    backgroundColor: "#fff",
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    height: 80,
    },
  title: {
    fontSize: 22,
    fontWeight: "800",
    color: "#292929",
    textAlign: "center",
  },
  titleIcons: {
    flexDirection: "row",
    gap: 18,
    position: "absolute",
    right: 24,
  },
  divider: {
    height: 3,
    backgroundColor: "#c4c4c4",
  },
  scrollArea: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  historyCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#e9e9eb",
    borderRadius: 13,
    padding: 16,
    height: 70,
  },
  cardContent: {
    flex: 1,
    gap: 6,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#292929",
  },
  cardDate: {
    fontSize: 10,
    color: "#6e6e6e",
  },
  startButton: {
    backgroundColor: "#2346A0",
    borderRadius: 48,
    height: 50,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 20,
    marginVertical: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
  },
  startButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    paddingHorizontal: 25,
    paddingTop: 140,
    paddingBottom: 40,
  },
  modalCard: {
    flex: 1,
    backgroundColor: "#fff",
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4.5 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
    overflow: "hidden",
  },
  deleteButton: {
    backgroundColor: "#ff4444",
    justifyContent: "center",
    alignItems: "center",
    width: 70,
    borderRadius: 13,
    height: 70,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    marginRight: 20,
    borderWidth: 2,
    borderColor: "#f0f0f0",
    borderRadius: 13,
    paddingHorizontal: 20,
    paddingVertical: 15,
    fontSize: 15,
    color: "#000",
  },
  highlightText: {
    color: "#004099",
    fontWeight: "700",
  },
  menuOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  sideMenu: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    width: "81%",
    backgroundColor: "#fff",
    paddingTop: 80,
    paddingHorizontal: 25,
    shadowColor: "#000",
    shadowOffset: { width: -4, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 10,
    borderTopLeftRadius: 50,
    borderBottomLeftRadius: 50,
  },
  menuHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 30,
  },
  menuTitle: {
    fontSize: 30,
    fontWeight: "700",
    color: "#004099",
  },
  menuSectionTitle: {
    fontSize: 12,
    color: "#999",
    fontWeight: "500",
  },
  menuItems: {
    gap: 21,
    flex: 1,
    paddingTop: 30,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  menuItemText: {
    fontSize: 17,
    color: "#292929",
    fontWeight: "500",
  },
  logoutItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingBottom: 70,
  },
  subMenuItems: {
    paddingLeft: 30,
    gap: 16,
    marginBottom: 4,
  },
  subMenuItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  subMenuItemText: {
    fontSize: 17,
    color: "#666",
    fontWeight: "500",
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 130,
    gap: 6,
  },
  emptyImage: {
    width: 130,
    height: 130,
    marginBottom: 10,
  },
  emptyImageWide: {
    width: 200,
    height: 150,
    marginBottom: 10,
  },
  emptyText: {
    fontSize: 15,
    color: "#666",
    textAlign: "center",
    fontWeight: "600",
  },
  emptySubText: {
    fontSize: 14,
    color: "#999",
    textAlign: "center",
    fontWeight: "500",
  },
  confirmOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  confirmBox: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    width: "100%",
    gap: 12,
  },
  confirmTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#292929",
    textAlign: "center",
  },
  confirmText: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    lineHeight: 22,
  },
  confirmButtons: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  confirmCancel: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
  },
  confirmCancelText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#666",
  },
  confirmDelete: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ff4444",
  },
  confirmDeleteText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#fff",
  },
});